### ISSUE TITLE
Why not sphinx-contrib?

### ISSUE THREAD

**Issue by jdillard** [sphinx-extensions2/.github#1]
> It is my hope that this may also encourage other to jump in as maintainers if they want.

Just curious, why not use the [sphinx-contrib](https://github.com/sphinx-contrib) org?

**Comment by chrisjsewell** [comment]
Well lets say, for now at least, I would rather keep administrative control 😅 
I've had my fill recently of being messed around in other organisations

**Comment by jdillard** [comment]
Ha fair enough!
